<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>__GROUP_ID__</groupId>
    <artifactId>__PROJECT_NAME__-metamodel-root</artifactId>
    <version>__VERSION__</version>
    <name>__PROJECT_NAME__-metamodel-root</name>
    <description>Generated EMF metamodel root for __PROJECT_NAME__</description>
    <packaging>pom</packaging>

    <modules>
        <module>__PROJECT_NAME__-metamodel</module>
        <module>__PROJECT_NAME__-metamodel-edit</module>
        <module>__PROJECT_NAME__</module>
    </modules>
</project>
